version: '3.8'

services:
  java:
    build: .
    command: sleep 3600
  db:
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sd
